#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(rgba32f, binding = 0) uniform readonly image2D uField;

layout(std430, binding = 1) buffer BoundaryVertices { vec2 data[]; } uBoundaryVertices;
layout(std430, binding = 2) buffer HorizontalEdgeIds { int data[]; } uHorizontalEdgeIds;
layout(std430, binding = 3) buffer VerticalEdgeIds   { int data[]; } uVerticalEdgeIds;
layout(std430, binding = 4) buffer VertexCounter     { uint count; } uVertexCounter;

uniform float uIso;
uniform ivec2 uChunkCoord;
uniform ivec2 uChunkGridSize;
uniform vec2  uChunkSize;
uniform vec2  uWorldCenter;
uniform vec2  uCellSize;

vec2 chunk_origin()
{
	return uWorldCenter +
		(vec2(float(uChunkCoord.x), float(uChunkCoord.y)) - 0.5 * vec2(float(uChunkGridSize.x), float(uChunkGridSize.y))) *
		uChunkSize;
}

float sample_field(ivec2 p)
{
    return imageLoad(uField, p).r;
}

vec2 grid_to_world(vec2 g)
{
	return chunk_origin() + g * uCellSize;
}

void main()
{
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(uField);

    if (id.x >= size.x || id.y >= size.y) return;

    if (id.x < size.x - 1)
    {
        float a = sample_field(id);
        float b = sample_field(id + ivec2(1, 0));

        bool ia = a >= uIso;
        bool ib = b >= uIso;

        uint index = id.y * (size.x - 1) + id.x;

        if (ia != ib)
        {
            float t = 0.5;
            float d = b - a;
            if (abs(d) > 1e-6)
                t = clamp((uIso - a) / d, 0.0, 1.0);

            vec2 pos = grid_to_world(vec2(id) + vec2(t, 0.0));

            uint v = atomicAdd(uVertexCounter.count, 1);
            uBoundaryVertices.data[v] = pos;
            uHorizontalEdgeIds.data[index] = int(v);
        }
        else uHorizontalEdgeIds.data[index] = -1;
    }

    if (id.y < size.y - 1)
    {
        float a = sample_field(id);
        float b = sample_field(id + ivec2(0, 1));

        bool ia = a >= uIso;
        bool ib = b >= uIso;

        uint index = id.y * size.x + id.x;

        if (ia != ib)
        {
            float t = 0.5;
            float d = b - a;
            if (abs(d) > 1e-6)
                t = clamp((uIso - a) / d, 0.0, 1.0);

            vec2 pos = grid_to_world(vec2(id) + vec2(0.0, t));

            uint v = atomicAdd(uVertexCounter.count, 1);
            uBoundaryVertices.data[v] = pos;
            uVerticalEdgeIds.data[index] = int(v);
        }
        else uVerticalEdgeIds.data[index] = -1;
    }
}
